name:                animation
version:             0.1.0.0
github:              "vallyscode/animation"
license:             BSD3
author:              "Valerii Lysenko"
maintainer:          "vallyscode@gmail.com"
copyright:           "2019 Valerii Lysenko"

data-files:
- resources/dino.png
- resources/tileset.png
- resources/Gladiator-Sprite Sheet.png

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/vallyscode/animation#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - text
  - mtl
  - sdl2
  - sdl2-image
  - sdl2-ttf
  - sdl2-mixer

executables:
  ex-01:
    main:                Main.hs
    source-dirs:         ex-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - animation
  ex-02:
    main:                Main.hs
    source-dirs:         ex-02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - animation
  ex-03:
    main:                Main.hs
    source-dirs:         ex-03
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - animation

tests:
  animation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - animation
